name: "Feature Implementation (AI-Ready)"
description: "Submit a proposal for a new feature or enhancement that's structured for AI processing"
title: "[Feature] "
labels: ["type:feature", "ai-ready"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Implementation Request
        Thank you for taking the time to fill out this feature implementation template! This format is optimized for AI agent processing.
        
  - type: input
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature to be implemented
      placeholder: "Example: Implement real-time beat detection algorithm"
    validations:
      required: true
      
  - type: textarea
    id: feature-description
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the proposed feature
      placeholder: "Describe the feature in detail, including its purpose and how it should work"
    validations:
      required: true
      
  - type: textarea
    id: tasks
    attributes:
      label: Implementation Tasks
      description: A clear list of tasks required to implement this feature
      placeholder: |
        - [ ] Task 1: Design the basic architecture
        - [ ] Task 2: Implement core functionality
        - [ ] Task 3: Add unit tests
        - [ ] Task 4: Document the feature
    validations:
      required: true
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Specific, measurable conditions that must be met for this feature to be considered complete
      placeholder: |
        - Feature should process audio in under 5ms per frame
        - Beat detection should have 95% accuracy
        - Memory usage should not exceed 50MB
    validations:
      required: true
      
  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: Specific technical details required for implementation
      placeholder: |
        - Implementation language: Swift 6
        - Required frameworks: Metal, AVFoundation
        - Performance constraints: Real-time processing
        - Threading requirements: Must be thread-safe
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component of the system does this feature belong to?
      options:
        - AudioProcessor
        - MLEngine
        - AudioBloomCore
        - Visualizer
        - AudioBloomUI
        - AudioBloomApp
        - Documentation
        - Testing
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority of this feature?
      options:
        - P0-critical
        - P1-high
        - P2-medium
        - P3-low
    validations:
      required: true
      
  - type: input
    id: dependencies
    attributes:
      label: Dependencies
      description: List any dependent features or issues (use GitHub issue numbers)
      placeholder: "#12, #15"
      
  - type: input
    id: milestone
    attributes:
      label: Milestone
      description: Which milestone or version is this feature targeting?
      placeholder: "Core Implementation (Phase 1)"
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: "Include any additional context, references, or design documents"

